version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: weekly
    day: sunday
    time: "22:00"
  open-pull-requests-limit: 99
  ignore:
  - dependency-name: "@types/mini-css-extract-plugin"
    versions:
    - 1.2.2
    - 1.4.0
    - 1.4.1
  - dependency-name: "@types/webpack"
    versions:
    - 4.41.26
    - 5.0.0
    - 5.28.0
  - dependency-name: "@types/eslint"
    versions:
    - 7.2.6
    - 7.2.7
    - 7.2.8
    - 7.2.9
  - dependency-name: "@babel/core"
    versions:
    - 7.12.10
    - 7.12.13
    - 7.12.16
    - 7.12.17
    - 7.13.10
    - 7.13.13
    - 7.13.14
    - 7.13.15
    - 7.13.8
  - dependency-name: y18n
    versions:
    - 4.0.1
  - dependency-name: "@types/file-loader"
    versions:
    - 4.2.1
  - dependency-name: "@types/webpack-dev-server"
    versions:
    - 3.11.1
    - 3.11.2
    - 3.11.3
  - dependency-name: eslint
    versions:
    - 7.18.0
    - 7.19.0
    - 7.20.0
    - 7.21.0
    - 7.22.0
    - 7.23.0
    - 7.24.0
  - dependency-name: ts-loader
    versions:
    - 8.0.14
    - 8.0.15
    - 8.0.17
    - 8.0.18
    - 8.1.0
  - dependency-name: webpack-cli
    versions:
    - 4.4.0
    - 4.5.0
    - 4.6.0
  - dependency-name: css-loader
    versions:
    - 5.0.1
    - 5.0.2
    - 5.1.0
    - 5.1.1
    - 5.1.2
    - 5.1.3
    - 5.2.0
    - 5.2.1
  - dependency-name: "@babel/preset-env"
    versions:
    - 7.12.11
    - 7.12.13
    - 7.12.16
    - 7.12.17
    - 7.13.10
    - 7.13.12
    - 7.13.15
    - 7.13.8
    - 7.13.9
  - dependency-name: mini-css-extract-plugin
    versions:
    - 1.3.4
    - 1.3.5
    - 1.3.6
    - 1.3.8
    - 1.3.9
    - 1.4.0
    - 1.4.1
  - dependency-name: "@types/copy-webpack-plugin"
    versions:
    - 6.4.0
    - 6.4.1
  - dependency-name: eslint-plugin-vue
    versions:
    - 7.5.0
    - 7.6.0
    - 7.7.0
    - 7.8.0
  - dependency-name: "@types/prettier"
    versions:
    - 2.1.6
    - 2.2.0
    - 2.2.1
    - 2.2.2
    - 2.2.3
  - dependency-name: "@types/babel__core"
    versions:
    - 7.1.12
    - 7.1.14
  - dependency-name: electron-builder
    versions:
    - 22.10.5
    - 22.9.1
  - dependency-name: vue-eslint-parser
    versions:
    - 7.4.1
    - 7.5.0
    - 7.6.0
  - dependency-name: typescript
    versions:
    - 4.1.3
    - 4.1.5
    - 4.2.2
    - 4.2.3
    - 4.2.4
  - dependency-name: vue-style-loader
    versions:
    - 4.1.3
  - dependency-name: "@babel/plugin-proposal-object-rest-spread"
    versions:
    - 7.12.1
    - 7.12.13
    - 7.13.8
  - dependency-name: eslint-config-prettier
    versions:
    - 7.2.0
    - 8.0.0
    - 8.1.0
  - dependency-name: "@babel/plugin-proposal-class-properties"
    versions:
    - 7.12.1
    - 7.12.13
    - 7.13.0
  - dependency-name: html-webpack-plugin
    versions:
    - 4.5.1
    - 4.5.2
  - dependency-name: sass
    versions:
    - 1.32.5
    - 1.32.6
    - 1.32.7
    - 1.32.8
  - dependency-name: lodash
    versions:
    - 4.17.20
    - 4.17.21
  - dependency-name: electron-rebuild
    versions:
    - 2.3.4
    - 2.3.5
  - dependency-name: elliptic
    versions:
    - 6.5.3
    - 6.5.4
  - dependency-name: vuex
    versions:
    - 3.6.0
    - 3.6.2
  - dependency-name: electron
    versions:
    - 9.3.1
    - 9.4.0
  - dependency-name: vue-router
    versions:
    - 3.4.9
    - 3.5.1
  - dependency-name: sass-loader
    versions:
    - 10.1.1
  - dependency-name: webpack-dev-server
    versions:
    - 3.11.2
  - dependency-name: fast-glob
    versions:
    - 3.2.5
  - dependency-name: webpack
    versions:
    - 4.46.0
  - dependency-name: eslint-plugin-prettier
    versions:
    - 3.3.1
  - dependency-name: electron-debug
    versions:
    - 3.2.0
  - dependency-name: vue-loader
    versions:
    - 15.9.6
  - dependency-name: copy-webpack-plugin
    versions:
    - 6.4.1
  - dependency-name: file-loader
    versions:
    - 6.2.0
  - dependency-name: "@types/babel__preset-env"
    versions:
    - 7.9.1
  - dependency-name: "@typescript-eslint/parser"
    versions:
    - 3.10.1
  - dependency-name: babel-loader
    versions:
    - 8.2.2
  - dependency-name: node-loader
    versions:
    - 1.0.2
    - 1.0.3
  - dependency-name: style-loader
    versions:
    - 2.0.0
  - dependency-name: url-loader
    versions:
    - 4.1.1
  - dependency-name: ini
    versions:
    - 1.3.8
  - dependency-name: prettier
    versions:
    - 2.2.1
  - dependency-name: "@typescript-eslint/eslint-plugin"
    versions:
    - 4.0.0
  - dependency-name: bulma-fluent
    versions:
    - 0.4.3
  - dependency-name: vue-template-compiler
    versions:
    - 2.6.12
  - dependency-name: vue
    versions:
    - 2.6.12
  - dependency-name: electron-devtools-installer
    versions:
    - 3.1.1
